name: Docker build
on:
    push
jobs:
    idle:
        name: Idle is doing only prints
        runs-on: ubuntu-latest
        steps:
            -
                name: checkout
                uses: actions/checkout@v4
            _
                name: docker build
                run: |
                    docker -t build cicd24 .
